### ISSUE TITLE
CPU usage hits 100% over time with no client connected

### ISSUE THREAD

**Issue by PWRxPSYCHO** [FreeTAKTeam/FreeTakServer#369] opened 2022-09-01 14:44 UTC
**Setup**
 - FreeTAKServer
 - FreeTAKServer UI
 Using Ubuntu 20.04.4 LTS (1 core, 1GB RAM cloud instance)
I have noticed the same behavior on a VM with 12 cores and 32GB RAM. 

Using Wireguard VPN as the main connection for server.
 
FTS is pointing to VPN address
FTS-UI is pointing to VPN address

WebMap is not installed nor is NodeRed

**_Server Idles at 27% directly after reboot but then over time it creeps up to 100%._**

HTOP shows that its FTS that is utilizing most of the CPU. No clients are connected during the time the server usage goes up.

UFW is setup to only allow connections through the VPN interface for the ports that FTS requires. 

FTS and FTS-UI are being run by using Systemd servivces:

FTS.service
```
[Unit]
Description=FreeTAK Server service
After=network.target
StartLimitIntervalSec=0

[Service]
Type=simple
Restart=always
RestartSec=1
ExecStart=/usr/bin/python3 -m FreeTAKServer.controllers.services.FTS -DataPackageIP <VPNAddress> -AutoStart True


[Install]
WantedBy=multi-user.target
```

FTS-UI.Service
```
[Unit]
Description=FreeTAK Server UI service
After=network.target
StartLimitIntervalSec=0

[Service]
Type=simple
Restart=always
RestartSec=1
ExecStart=sudo python3 /usr/local/lib/python3.8/dist-packages/FreeTAKServer-UI/run.py

[Install]
WantedBy=multi-user.target
```

**Comment by brothercorvo** [comment] 2022-09-05 17:32
this was provoked by the users having multiple FTS services running in parallel. @HeroesLament please copy here some of the solution and close the issue

**Closed** 2022-09-14 17:47 UTC
Labels: wontfix

**Comment by b1uebu11** [comment] 2022-11-21 11:22
@PWRxPSYCHO Hey mate, I had this problem as well on a xubuntu build, I used 'cpulimit'. 
Installed using 'sudo apt install cpulimit', then you just find the service PID number with another program called 'htop' (might have to install that as well if not already installed).
then enter sudo cpulimit --pid <pid of app, e.g. 1121> --limit <enter cpu % here e.g. 50 for 50%) --background

**Comment by brothercorvo** [comment] 2022-11-21 12:00
CPU limit would hide the symptom, without addressing the cause of the issue.
