### ISSUE TITLE
Team Geochat has issues

### ISSUE THREAD

**Issue by pratimakulkarni** [FreeTAKTeam/FreeTakServer#336] opened 2022-05-16 13:30 UTC
Hi, i am trying to send chat message from Team ( Eg: Red ). 

Issue : Some users receive the message from Team chat , others who belong to team don't receive.

Communication : Wintak to my application and  Vise versa in Team chat /  Atak member message in Team chat.

Connection : Tested connecting to Community TAK Server and also on Local FreeTAKServer Version 1.9.8.8

Details : 
- connected wintak , my application , atak to free tak server,
- All 3 clients belong to Team Red.
-  Able to see all geolocations in each others map.
- Able to see in contacts and in team.
- When message is sent from Team chat , any of single user gets message and the other connected members wont receive the cot message itself.
- Further on debugging checked that <dest> in marti does not have all users but sends to single user.

Cot message sent from wintak to FTAK : 

`<event version="2.0" uid="GeoChat.S-1-5-21-2151449903-2689254037-3848131860-1001.Red.7043930b-f045-44a4-9ec8-d950ded9dcb7" type="b-t-f" time="2022-05-16T13:24:59.71Z" start="2022-05-16T13:24:59.71Z" 
stale="2022-05-17T13:24:59.71Z" how="h-g-i-g-o">
	<point lat="0" lon="0" hae="9999999" ce="9999999" le="9999999" />
	<detail>
		<__chat id="Red" chatroom="Red" senderCallsign="Wintak" groupOwner="false">
			<chatgrp id="Red" uid0="S-1-5-21-2151449903-2689254037-3848131860-1001" uid1="user1" uid2="user2" />
			<hierarchy>
				<group uid="TeamGroups" name="Teams">
					<group uid="Red" name="Red">
						<contact uid="S-1-5-21-2151449903-2689254037-3848131860-1001" name="Wintak" />
					</group>
				</group>
			</hierarchy>
		</__chat>
		<link uid="S-1-5-21-2151449903-2689254037-3848131860-1001" type="a-f-G-U-C-I" relation="p-p" />
		<remarks source="BAO.F.WinTAK.S-1-5-21-2151449903-2689254037-3848131860-1001" sourceID="S-1-5-21-2151449903-2689254037-3848131860-1001" to="Red" time="2022-05-16T13:24:59.71Z">Test message from wintak in team </remarks>
		<marti>
			<dest callsign="user2" />
		</marti>
	</detail>
</event>`

- Then i tested on my local Free tak server , where it is throwing this issue.

`data received b'<event version="2.0" uid="GeoChat.S-1-5-21-2151449903-2689254037-3848131860-1001.Red.a9583f42-464e-4cb0-9b07-a717108be32b" type="b-t-f" time="2022-05-16T13:24:10.74Z" start="2022-05-16T13:24:10.74Z" stale="2022-05-17T13:24:10.74Z" how="h-g-i-g-o"><point lat="0" lon="0" hae="9999999" ce="9999999" le="9999999" /><detail><__chat id="Red" chatroom="Red" senderCallsign="Wintak" groupOwner="false"><chatgrp id="Red" uid0="S-1-5-21-2151449903-2689254037-3848131860-1001" uid1="user1" uid2="user2" /><hierarchy><group uid="TeamGroups" name="Teams"><group uid="Red" name="Red"><contact uid="S-1-5-21-2151449903-2689254037-3848131860-1001" name="Wintak" /></group></group></hierarchy></__chat><link uid="S-1-5-21-2151449903-2689254037-3848131860-1001" type="a-f-G-U-C-I" relation="p-p" /><remarks source="BAO.F.WinTAK.S-1-5-21-2151449903-2689254037-3848131860-1001" sourceID="S-1-5-21-2151449903-2689254037-3848131860-1001" to="Red" time="2022-05-16T13:24:10.74Z">Test message from wintak in team</remarks><marti><dest callsign="user2" /></marti></detail></event>'
handling reg data
<FreeTAKServer.model.FTSModel.Chatgrp.Chatgrp object at 0x0000021056052250>
the following property is missing from the FTS model missing cot: b'<chatgrp id="Red" uid0="S-1-5-21-2151449903-2689254037-3848131860-1001" uid1="user1" uid2="user2" />' attr: uid2 please open an issue on the FTS github page with this message so that we can address it in future releases
<FreeTAKServer.model.FTSModel.Chatgrp.Chatgrp object at 0x0000021056052250>
the following tag is missing from the FTS model, missing cot b'<_chat id="Red" chatroom="Red" senderCallsign="Wintak" groupOwner="false"><chatgrp id="Red" uid0="S-1-5-21-2151449903-2689254037-3848131860-1001" 
uid1="user1" uid2="user2" /><hierarchy><group uid="TeamGroups" name="Teams"><group uid="Red" name="Red"><contact uid="S-1-5-21-2151449903-2689254037-3848131860-1001" name="Wintak" /></group></group></hierarchy></_chat>' missing tag name: hierarchy`

**Comment by brothercorvo** [comment] 2022-05-16 14:22
@naman108 please add attr: uid2  to the domain model

**Comment by pratimakulkarni** [comment] 2022-05-17 07:08
@brothercorvo  : uid1 , uid2 is dynamic right , based on the number of members in team ? So it can uid1, uid2 ....... uidN . Also i observe that in <marti> , <dest> has to be multiple based on number of users. It always adds single user even though we have multiple members in team.

**Comment by brothercorvo** [comment] 2022-09-06 12:33
@pratimakulkarni the issue appears to be fixed in the code, can yo confirm this?

**Comment by pratimakulkarni** [comment] 2022-09-07 08:19
@brothercorvo : I installed FreeTAKServer version 1.9.9.6  and checked the team chat, seems like its not yet working. 
Also i tried connecting Wintak and my application to public free tak server ie - 204.48.30.216 , yet the issue remains same. 

Is this correct way, or you want me to check in some other way ? Should i see some specific other version , please let me know. Thanks. 

Problem persist : Feels like uid attribute is not fixed. Still it is taking just uid1 i.e only 1 user. So if there are multiple users it has to take those many uids like uid1, uid2 , uid3 and so on , as many users present in team.

Pasted the COT message that i recieved from FreeTAK when message was sent to team. 

This message was sent from Wintak to other members of Red Team. Also same was tried from my application to Red team.
In both case only 1 user got the message among 4 users.

```<event version="2.0" uid="GeoChat.S-1-5-21-2151449903-2689254037-3848131860-1001.Red.b4befd75-3641-4ea7-ae82-0ae481adf822" type="b-t-f" how="h-g-i-g-o" start="2022-09-07T08:00:13.44Z" time="2022-09-07T08:00:13.44Z" stale="2022-09-08T08:00:13.44Z"><detail><__chat id="Red" chatroom="Red" groupOwner="false">**<chatgrp uid0="S-1-5-21-2151449903-2689254037-3848131860-1001" uid1="f5b56ca3-6004-416b-9023-d8ee134f4804" id="Red" />**</__chat><link uid="S-1-5-21-2151449903-2689254037-3848131860-1001" relation="p-p" type="a-f-G-U-C-I" /><remarks time="2022-09-07T08:00:13.44Z" source="BAO.F.WinTAK.S-1-5-21-2151449903-2689254037-3848131860-1001" sourceID="S-1-5-21-2151449903-2689254037-3848131860-1001" to="Red">test red team message</remarks><__serverdestination /><marti><dest callsign="pratima" /><dest callsign="swaroop" /><dest callsign="praveen.d" /><dest /></marti></detail><point le="9999999" ce="9999999" hae="9999999" lon="0" lat="0" /></event>```

**Comment by naman108** [comment] 2022-09-09 02:28
the issue is due to the fact that currently uid0 and uid1 are hardcoded attributes in the chatgrp model https://github.com/FreeTAKTeam/FreeTakServer/blob/29e3e48fa49972dd021218a6d44d5750c47e8c76/FreeTAKServer/model/FTSModel/Chatgrp.py#L14-L17

I see two solutions which could be applied prior to v 2.0
1. we implement some way to dynamically add these uid variables of changing value
2. we ignore the uid based approach to forwarding cot's for the time being and stick with the marti tag
@brothercorvo what do you think?

**Comment by pratimakulkarni** [comment] 2022-09-09 04:04
@naman108 ya true that's what I saw that uid 0 and 1 is hard-coded and is not dynamic hence it's taking just one user. Yeh as you said we have to ignore or make it dynamic. Thanks for pointing at code to refer.

**Comment by brothercorvo** [comment] 2022-10-12 12:27
this should be l;inked to the Chat component release

**Closed** 2023-05-21 21:40 UTC
Labels: bug_minor
