### ISSUE TITLE
ImportError: cannot import name 'json' from 'itsdangerous'

### ISSUE THREAD

**Issue by hiddenterror** [FreeTAKTeam/FreeTakServer#296] opened 2022-02-25 01:39 UTC
I followed the document to install FreeTAKServer on Ubuntu 20.04.  However, when I try to start the service, I receive the error from the title (see below).

> Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/FreeTAKServer/controllers/services/FTS.py", line 6, in <module>
    from FreeTAKServer.controllers.services.TCPDataPackageService import TCPDataPackageService as TCPFlaskFunctions
  File "/usr/local/lib/python3.8/dist-packages/FreeTAKServer/controllers/services/TCPDataPackageService.py", line 1, in <module>
    from .DataPackageServer import FlaskFunctions, Path, dp_directory, os, app, eventlet, const
  File "/usr/local/lib/python3.8/dist-packages/FreeTAKServer/controllers/services/DataPackageServer.py", line 13, in <module>
    from FreeTAKServer.controllers.DatabaseControllers.DatabaseController import DatabaseController
  File "/usr/local/lib/python3.8/dist-packages/FreeTAKServer/controllers/DatabaseControllers/DatabaseController.py", line 1, in <module>
    import FreeTAKServer.controllers.DatabaseControllers.table_controllers
  File "/usr/local/lib/python3.8/dist-packages/FreeTAKServer/controllers/DatabaseControllers/table_controllers.py", line 3, in <module>
    from FreeTAKServer.model.SQLAlchemy.User import User
  File "/usr/local/lib/python3.8/dist-packages/FreeTAKServer/model/SQLAlchemy/User.py", line 18, in <module>
    from FreeTAKServer.model.SQLAlchemy.system_user import SystemUser
  File "/usr/local/lib/python3.8/dist-packages/FreeTAKServer/model/SQLAlchemy/system_user.py", line 6, in <module>
    from flask_login import UserMixin
  File "/usr/local/lib/python3.8/dist-packages/flask_login/__init__.py", line 16, in <module>
    from .login_manager import LoginManager
  File "/usr/local/lib/python3.8/dist-packages/flask_login/login_manager.py", line 12, in <module>
    from flask import (_request_ctx_stack, abort, current_app, flash, redirect,
  File "/usr/local/lib/python3.8/dist-packages/flask/__init__.py", line 19, in <module>
    from . import json
  File "/usr/local/lib/python3.8/dist-packages/flask/json/__init__.py", line 15, in <module>
    from itsdangerous import json as _json
ImportError: cannot import name 'json' from 'itsdangerous' (/usr/local/lib/python3.8/dist-packages/itsdangerous/__init__.py)

It seems as though this issue may be related to an issue with Flask (https://github.com/pallets/flask/issues/4455) and the only recommended fix at this time is to upgrade Flask (which gives an error as it is not compatible with FreeTAKServer.  Downgrading itsdangerous and markupsafe did not seem to resolve the issue.  I have rolled back the VM multiple times and started fresh, but the error has occurred every time.

**Comment by brothercorvo** [comment] 2022-02-25 12:55
have you tried with the zero touch install?

**Comment by kk6lzb** [comment] 2022-02-25 13:23
I'm also getting the same error after downgrading markupsafe to 2.0.1. I have not tried the zero touch install, though.

**Comment by jmarcorb** [comment] 2022-02-26 21:33
I can confirm this. It happened to me yesterday in a fresh Ubuntu 20.04 install. Also with the Hub installer.
I tried multiple combinations of markupsafe, itsdangerous and Flask versions, but to no avail.

**Comment by brothercorvo** [comment] 2022-02-28 13:10
Ok we are going to investigate this @naman108 and @jonaugustine . It looks like an issue with dependencies

**Comment by brothercorvo** [comment] 2022-03-12 17:49
fixed in 1.9.8.5

**Closed by brothercorvo** 2022-03-12 17:49 UTC
Labels: bug_Normal
